server:
#  tomcat:
#    accept-count: 5000   # 队列容量
#    threads:
#      max: 2000
#      min-spare: 500
#    max-connections: 20000

  port: 8080
  servlet:
    session:
      timeout: 60m
spring:
  profiles:
    active: gateway
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/lottery?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://192.168.247.133:3306/lottery?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
#      sentinel:
#        master: mymaster
#        nodes:
#          - 127.0.0.1:17001
#          - 127.0.0.1:17002
#          - 127.0.0.1:17003
#        password: 123456

      host: localhost
      port: 6379
      password: 123456
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            misfireThreshold: 60000
            #一分钟的容忍，超出就按超时处理
          scheduler:
            instanceName: LotteryScheduler

  rabbitmq:
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
    host: 192.168.247.133
    port: 5672
    virtual-host: /lottery
    username: TWind
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          stateless: true
        acknowledge-mode: auto
  application:
    name: lottery-server

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info